name: seismo-rain-analytics-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - plotly
  - jupyterlab
  - pyproj
  - contextily
  - pip
  - pip:
      # Añade aquí paquetes pip si se requieren más adelante
